/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Board */

#ifndef _Included_Board
#define _Included_Board
#ifdef __cplusplus
extern "C" {
#endif
#undef Board_FOCUS_TRAVERSABLE_UNKNOWN
#define Board_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef Board_FOCUS_TRAVERSABLE_DEFAULT
#define Board_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef Board_FOCUS_TRAVERSABLE_SET
#define Board_FOCUS_TRAVERSABLE_SET 2L
#undef Board_TOP_ALIGNMENT
#define Board_TOP_ALIGNMENT 0.0f
#undef Board_CENTER_ALIGNMENT
#define Board_CENTER_ALIGNMENT 0.5f
#undef Board_BOTTOM_ALIGNMENT
#define Board_BOTTOM_ALIGNMENT 1.0f
#undef Board_LEFT_ALIGNMENT
#define Board_LEFT_ALIGNMENT 0.0f
#undef Board_RIGHT_ALIGNMENT
#define Board_RIGHT_ALIGNMENT 1.0f
#undef Board_serialVersionUID
#define Board_serialVersionUID -7644114512714619750LL
#undef Board_serialVersionUID
#define Board_serialVersionUID 4613797578919906343LL
#undef Board_INCLUDE_SELF
#define Board_INCLUDE_SELF 1L
#undef Board_SEARCH_HEAVYWEIGHTS
#define Board_SEARCH_HEAVYWEIGHTS 1L
#undef Board_NOT_OBSCURED
#define Board_NOT_OBSCURED 0L
#undef Board_PARTIALLY_OBSCURED
#define Board_PARTIALLY_OBSCURED 1L
#undef Board_COMPLETELY_OBSCURED
#define Board_COMPLETELY_OBSCURED 2L
#undef Board_WHEN_FOCUSED
#define Board_WHEN_FOCUSED 0L
#undef Board_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define Board_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef Board_WHEN_IN_FOCUSED_WINDOW
#define Board_WHEN_IN_FOCUSED_WINDOW 2L
#undef Board_UNDEFINED_CONDITION
#define Board_UNDEFINED_CONDITION -1L
#undef Board_IS_DOUBLE_BUFFERED
#define Board_IS_DOUBLE_BUFFERED 0L
#undef Board_ANCESTOR_USING_BUFFER
#define Board_ANCESTOR_USING_BUFFER 1L
#undef Board_IS_PAINTING_TILE
#define Board_IS_PAINTING_TILE 2L
#undef Board_IS_OPAQUE
#define Board_IS_OPAQUE 3L
#undef Board_KEY_EVENTS_ENABLED
#define Board_KEY_EVENTS_ENABLED 4L
#undef Board_FOCUS_INPUTMAP_CREATED
#define Board_FOCUS_INPUTMAP_CREATED 5L
#undef Board_ANCESTOR_INPUTMAP_CREATED
#define Board_ANCESTOR_INPUTMAP_CREATED 6L
#undef Board_WIF_INPUTMAP_CREATED
#define Board_WIF_INPUTMAP_CREATED 7L
#undef Board_ACTIONMAP_CREATED
#define Board_ACTIONMAP_CREATED 8L
#undef Board_CREATED_DOUBLE_BUFFER
#define Board_CREATED_DOUBLE_BUFFER 9L
#undef Board_IS_PRINTING
#define Board_IS_PRINTING 11L
#undef Board_IS_PRINTING_ALL
#define Board_IS_PRINTING_ALL 12L
#undef Board_IS_REPAINTING
#define Board_IS_REPAINTING 13L
#undef Board_WRITE_OBJ_COUNTER_FIRST
#define Board_WRITE_OBJ_COUNTER_FIRST 14L
#undef Board_RESERVED_1
#define Board_RESERVED_1 15L
#undef Board_RESERVED_2
#define Board_RESERVED_2 16L
#undef Board_RESERVED_3
#define Board_RESERVED_3 17L
#undef Board_RESERVED_4
#define Board_RESERVED_4 18L
#undef Board_RESERVED_5
#define Board_RESERVED_5 19L
#undef Board_RESERVED_6
#define Board_RESERVED_6 20L
#undef Board_WRITE_OBJ_COUNTER_LAST
#define Board_WRITE_OBJ_COUNTER_LAST 21L
#undef Board_REQUEST_FOCUS_DISABLED
#define Board_REQUEST_FOCUS_DISABLED 22L
#undef Board_INHERITS_POPUP_MENU
#define Board_INHERITS_POPUP_MENU 23L
#undef Board_OPAQUE_SET
#define Board_OPAQUE_SET 24L
#undef Board_AUTOSCROLLS_SET
#define Board_AUTOSCROLLS_SET 25L
#undef Board_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define Board_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef Board_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define Board_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
/*
 * Class:     Board
 * Method:    createBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Board_createBoard
  (JNIEnv *, jobject);

/*
 * Class:     Board
 * Method:    deleteBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Board_deleteBoard
  (JNIEnv *, jobject);

/*
 * Class:     Board
 * Method:    getColor
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_Board_getColor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Board
 * Method:    getType
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_Board_getType
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Board
 * Method:    getCheckmate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Board_getCheckmate
  (JNIEnv *, jobject);

/*
 * Class:     Board
 * Method:    verifyMove
 * Signature: ([I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_Board_verifyMove
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
