/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChessPanel */

#ifndef _Included_ChessPanel
#define _Included_ChessPanel
#ifdef __cplusplus
extern "C" {
#endif
#undef ChessPanel_FOCUS_TRAVERSABLE_UNKNOWN
#define ChessPanel_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef ChessPanel_FOCUS_TRAVERSABLE_DEFAULT
#define ChessPanel_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef ChessPanel_FOCUS_TRAVERSABLE_SET
#define ChessPanel_FOCUS_TRAVERSABLE_SET 2L
#undef ChessPanel_TOP_ALIGNMENT
#define ChessPanel_TOP_ALIGNMENT 0.0f
#undef ChessPanel_CENTER_ALIGNMENT
#define ChessPanel_CENTER_ALIGNMENT 0.5f
#undef ChessPanel_BOTTOM_ALIGNMENT
#define ChessPanel_BOTTOM_ALIGNMENT 1.0f
#undef ChessPanel_LEFT_ALIGNMENT
#define ChessPanel_LEFT_ALIGNMENT 0.0f
#undef ChessPanel_RIGHT_ALIGNMENT
#define ChessPanel_RIGHT_ALIGNMENT 1.0f
#undef ChessPanel_serialVersionUID
#define ChessPanel_serialVersionUID -7644114512714619750LL
#undef ChessPanel_serialVersionUID
#define ChessPanel_serialVersionUID 4613797578919906343LL
#undef ChessPanel_INCLUDE_SELF
#define ChessPanel_INCLUDE_SELF 1L
#undef ChessPanel_SEARCH_HEAVYWEIGHTS
#define ChessPanel_SEARCH_HEAVYWEIGHTS 1L
#undef ChessPanel_NOT_OBSCURED
#define ChessPanel_NOT_OBSCURED 0L
#undef ChessPanel_PARTIALLY_OBSCURED
#define ChessPanel_PARTIALLY_OBSCURED 1L
#undef ChessPanel_COMPLETELY_OBSCURED
#define ChessPanel_COMPLETELY_OBSCURED 2L
#undef ChessPanel_WHEN_FOCUSED
#define ChessPanel_WHEN_FOCUSED 0L
#undef ChessPanel_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define ChessPanel_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef ChessPanel_WHEN_IN_FOCUSED_WINDOW
#define ChessPanel_WHEN_IN_FOCUSED_WINDOW 2L
#undef ChessPanel_UNDEFINED_CONDITION
#define ChessPanel_UNDEFINED_CONDITION -1L
#undef ChessPanel_IS_DOUBLE_BUFFERED
#define ChessPanel_IS_DOUBLE_BUFFERED 0L
#undef ChessPanel_ANCESTOR_USING_BUFFER
#define ChessPanel_ANCESTOR_USING_BUFFER 1L
#undef ChessPanel_IS_PAINTING_TILE
#define ChessPanel_IS_PAINTING_TILE 2L
#undef ChessPanel_IS_OPAQUE
#define ChessPanel_IS_OPAQUE 3L
#undef ChessPanel_KEY_EVENTS_ENABLED
#define ChessPanel_KEY_EVENTS_ENABLED 4L
#undef ChessPanel_FOCUS_INPUTMAP_CREATED
#define ChessPanel_FOCUS_INPUTMAP_CREATED 5L
#undef ChessPanel_ANCESTOR_INPUTMAP_CREATED
#define ChessPanel_ANCESTOR_INPUTMAP_CREATED 6L
#undef ChessPanel_WIF_INPUTMAP_CREATED
#define ChessPanel_WIF_INPUTMAP_CREATED 7L
#undef ChessPanel_ACTIONMAP_CREATED
#define ChessPanel_ACTIONMAP_CREATED 8L
#undef ChessPanel_CREATED_DOUBLE_BUFFER
#define ChessPanel_CREATED_DOUBLE_BUFFER 9L
#undef ChessPanel_IS_PRINTING
#define ChessPanel_IS_PRINTING 11L
#undef ChessPanel_IS_PRINTING_ALL
#define ChessPanel_IS_PRINTING_ALL 12L
#undef ChessPanel_IS_REPAINTING
#define ChessPanel_IS_REPAINTING 13L
#undef ChessPanel_WRITE_OBJ_COUNTER_FIRST
#define ChessPanel_WRITE_OBJ_COUNTER_FIRST 14L
#undef ChessPanel_RESERVED_1
#define ChessPanel_RESERVED_1 15L
#undef ChessPanel_RESERVED_2
#define ChessPanel_RESERVED_2 16L
#undef ChessPanel_RESERVED_3
#define ChessPanel_RESERVED_3 17L
#undef ChessPanel_RESERVED_4
#define ChessPanel_RESERVED_4 18L
#undef ChessPanel_RESERVED_5
#define ChessPanel_RESERVED_5 19L
#undef ChessPanel_RESERVED_6
#define ChessPanel_RESERVED_6 20L
#undef ChessPanel_WRITE_OBJ_COUNTER_LAST
#define ChessPanel_WRITE_OBJ_COUNTER_LAST 21L
#undef ChessPanel_REQUEST_FOCUS_DISABLED
#define ChessPanel_REQUEST_FOCUS_DISABLED 22L
#undef ChessPanel_INHERITS_POPUP_MENU
#define ChessPanel_INHERITS_POPUP_MENU 23L
#undef ChessPanel_OPAQUE_SET
#define ChessPanel_OPAQUE_SET 24L
#undef ChessPanel_AUTOSCROLLS_SET
#define ChessPanel_AUTOSCROLLS_SET 25L
#undef ChessPanel_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define ChessPanel_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef ChessPanel_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define ChessPanel_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
/*
 * Class:     ChessPanel
 * Method:    printClick
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ChessPanel_printClick
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
